name: 'Publish to Steam'

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      postfix:
        required: false
        type: string
        default: ''

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: '*${{ inputs.postfix }}'
      
      - uses: game-ci/steam-deploy@v3
        with:
          username: ${{ secrets.STEAM_USERNAME }}          
          configVdf: ${{ secrets.CONFIGVDF }}
          appId: 2108550
          buildDescription: 'Automatic deployment (${{ inputs.branch }})'
          depot3Path: 'build-win32${{ inputs.postfix }}/out/'
          depot4Path: 'build-linux${{ inputs.postfix }}/out/'
          depot5Path: 'build-osx${{ inputs.postfix }}/out/'
          releaseBranch: '${{ inputs.branch }}'